config/routes.rb
AcDP::Application.routes.draw do
  opinio_model

  resources :news_posts do
    member do
      delete 'icon'
    end
    collection do
      get 'tags/:tag' => 'news_posts#index', as: 'tag'
      get 'categories/:category' => 'news_posts#index', as: 'category'
      get 'categories/group/:group_id' => 'news_posts#index', as: 'group'
    end
  end

  get 'calendar', to: 'calendar'
  get 'calendar/day/:date', to: 'calendar#day', as: 'day'

  get 'documents/sidebar_info' => 'documents#sidebar_info', as: 'documents_sidebar_info'
  get 'documents', to: 'documents#index'
  get 'documents/search' => 'documents#search', as: 'doc_search'
  get 'documents/shared', to: 'documents#shared', as: 'doc_shared'
  # get 'documents/shared/:user_id', to: 'documents#shared', as: 'document_shared_root'
  # get 'documents/shared/:user_id/:id', to: 'documents#shared', as: 'document_shared'
  get 'documents/get_file_info', to: 'documents#get_file_doc_id', as: 'get_file_doc_id'
  get 'documents/:id', to: 'documents#index', as: 'document'

  post 'documents', to: 'documents#new', as: 'new_document'
  post 'documents/:id', to: 'documents#new', as: 'document_new'
  post 'documents/change_file', to: 'documents#change_file'

  patch 'documents/:id', to: 'documents#update'

  delete 'documents/:id/delete', to: 'documents#delete', as: 'document_delete'

  root "users#dashboard"

  devise_for :users

  namespace :admin do
    resources :users do
      member do
        delete "avatar"
      end
    end
    resources :groups
    resources :doctypes
  end

  get 'dashboard' => "users#dashboard", as: :dashboard

  resources :users, only: [:show] do
  	collection do
      get 'current/edit' => "users#edit_current", as: :current_user_edit
      patch 'current' => "users#update_current", as: :current_user_update
      delete 'current' => "users#avatar", as: :current_user_avatar
  	end
  end

  resources :conversations, only: [:create, :index, :destroy] do
    resources :messages, only: [:index, :create]
  end

  post 'conversations/:id/attach_doc/:doc_id' => 'conversations#attach_doc', as: :conv_doc_attach
  post 'conversations/:id/detach_doc/:doc_id' => 'conversations#detach_doc', as: :conv_doc_detach

  resources :contacts, only: [:index, :create, :destroy]

  resources :tasks
  post 'tasks/:id' => 'tasks#update_checklist', as: :update_checklist

  resources :events

  get 'activity' => 'application#panel_activity', as: :activity_popover
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_many :messages, -> { order "created_at ASC" }, dependent: :destroy
	has_many :subscriptions, dependent: :destroy
	has_many :participants, through: :subscriptions, source: :user

  has_and_belongs_to_many :documents, join_table: :conversations_documents
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.create(conversation_params)
    handle_errors
    params[:receiver_ids] ||= []
    members_ids = params[:receiver_ids].push(current_user.id)
    members = User.where(id: members_ids)
    @conversation.participants = members
    @conversation.messages.build({ body: params[:message][:body], author: current_user })

    if @conversation.save
      redirect_to conversations_path, notice: t('messages.notice.send')
    else
      handle_errors
      @conversation.destroy
      redirect_to :back
    end
  end

  def index
    @conversations = Conversation.find(current_user
      .subscriptions.pluck(:conversation_id))
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    (@conversation.subscriptions.find_by user: current_user).destroy
    @conversation.destroy if @conversation.subscriptions.empty?
    redirect_to :back
  end

  def attach_doc
    @conversation = Conversation.find(params[:id])
    @document = Document.find(params[:doc_id])
    if not @conversation.documents.include? @document
      @conversation.documents << @document
      render json: {message: 'Document was successfully attached', status: 200}
    else
      render json: {message: 'Document already attached', status: 204}
    end
  end

  def detach_doc
    @conversation = Conversation.find(params[:id])
    @document = Document.find(params[:doc_id])
    if @conversation.documents.include? @document
      @conversation.documents.delete(@document)
      render json: {message: 'Document was successfully detached'}, status: 204
    else
      render json: {message: 'Document is not attached'}, status: 404
    end
  end

  private
  def conversation_params
    params.require(:conversation).permit(:subject)
  end

  def handle_errors
    if @conversation.errors.any?
      flash[:error] = t('messages.notice.error_send')
    end
  end
end

app/views/conversations/_new_conversation_button.html.erb
<div class="ui positive icon labeled fluid button modalSend">
  <i class="mail icon"></i>
  <%= local_assigns[:button_text] || t('messages.send') %>
</div>

<%= render partial: "conversations/new_conversation_modal", locals: {
      conversation: Conversation.new,
      receiver_ids: receiver_ids,
      modal_title: local_assigns[:modal_title] || t('messages.new')
    } %>

app/views/conversations/_new_conversation_modal.html.erb
<div class="ui modal" id="conversationOpen">
  <i class="close icon"></i>
  <div class="header"><%= modal_title %></div>
  <div id="content" class="content">
    <%= form_for conversation, method: :post, html: { class: 'ui fluid form segment' } do |f| %>
      <div class="field">
        <%= f.label t('messages.subject') %>
        <%= f.text_field :subject %>
      </div>
      <div class="field">
        <%= f.label t('messages.receivers') %>
        <%= select_tag :receiver_ids, options_for_select(User.all.reject { |u| u == current_user }.map { |u| [u.full_name, u.id] }, receiver_ids), { class: "chosen-select", multiple: true, include_blank: true } %>  
      </div>
      <div class="field">
        <%= f.label t('messages.message') %>
        <%= text_area "message", :body %>
      </div>
      <%= f.submit class: "ui positive button", value: t('messages.send') %>
    <% end %>    
  </div>
</div>

app/views/conversations/index.html.erb
<% if not @conversations.empty? %>
  <table class="dialogs ui table padded blue segment table-hover">
    <thead>
      <tr>
        <th><%= t('conversations.subject') %></th>
        <th><%= t('conversations.participants') %></th>
        <th><%= t('conversations.last_message') %></th>
        <th class="c-admin-users-actions-column"><%= t('util.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <% @conversations.each do |conversation| %>
        <tr data-link=<%= conversation_messages_path(conversation_id: conversation.id) %>>
          <td>
            <%= !conversation.subject.empty? ? conversation.subject : "(no topic)" %>
            <% if (umc = conversation.subscriptions.find_by(user: current_user).unread_messages_count) != 0 %>
              <div class="ui teal red label"><%= umc %></div>
            <% end  %>
          </td>
          <td>
            <% for p in Array(conversation.participants) do %>
              <% if p != current_user %>
                <%= link_to image_tag(p.avatar.url("small"), class: 'c-user-small-avatar',
                  title: p.full_name), user_path(p.id) %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to image_tag((mes = conversation.messages.last).author.avatar.url("small"),
              class: 'c-user-small-avatar', title: mes.author.full_name), user_path(mes.author.id) %>
            <span><%= (lm = mes.body).length > 70 ? lm[0..70] << "..." : lm %></span>
          </td>
          <td>
            <%= link_to conversation_path(conversation), method: :delete, class: "mini ui icon button" do %>
              <i class="icon close"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="ui info message no-conversations"><%= t('conversations.no_conversations') %></p>
  <p class="text-center">
    <%= render partial: "conversations/new_conversation_button", locals: {
          receiver_ids: [],
          modal_title: t('conversations.new'),
          button_text: t('conversations.new_conversation')
        } %>
  </p>
<% end %>