config/routes.rb
AcDP::Application.routes.draw do
  opinio_model

  resources :news_posts do
    member do
      delete 'icon'
    end
    collection do
      get 'tags/:tag' => 'news_posts#index', as: 'tag'
      get 'categories/:category' => 'news_posts#index', as: 'category'
      get 'categories/group/:group_id' => 'news_posts#index', as: 'group'
    end
  end

  get 'calendar', to: 'calendar'
  get 'calendar/day/:date', to: 'calendar#day', as: 'day'

  get 'documents/sidebar_info' => 'documents#sidebar_info', as: 'documents_sidebar_info'
  get 'documents', to: 'documents#index'
  get 'documents/search' => 'documents#search', as: 'doc_search'
  get 'documents/shared', to: 'documents#shared', as: 'doc_shared'
  # get 'documents/shared/:user_id', to: 'documents#shared', as: 'document_shared_root'
  # get 'documents/shared/:user_id/:id', to: 'documents#shared', as: 'document_shared'
  get 'documents/get_file_info', to: 'documents#get_file_doc_id', as: 'get_file_doc_id'
  get 'documents/:id', to: 'documents#index', as: 'document'

  post 'documents', to: 'documents#new', as: 'new_document'
  post 'documents/:id', to: 'documents#new', as: 'document_new'
  post 'documents/change_file', to: 'documents#change_file'

  patch 'documents/:id', to: 'documents#update'

  delete 'documents/:id/delete', to: 'documents#delete', as: 'document_delete'

  root "users#dashboard"

  devise_for :users

  namespace :admin do
    resources :users do
      member do
        delete "avatar"
      end
    end
    resources :groups
    resources :doctypes
  end

  get 'dashboard' => "users#dashboard", as: :dashboard

  resources :users, only: [:show] do
  	collection do
      get 'current/edit' => "users#edit_current", as: :current_user_edit
      patch 'current' => "users#update_current", as: :current_user_update
      delete 'current' => "users#avatar", as: :current_user_avatar
  	end
  end

  resources :conversations, only: [:create, :index, :destroy] do
    resources :messages, only: [:index, :create]
  end

  post 'conversations/:id/attach_doc/:doc_id' => 'conversations#attach_doc', as: :conv_doc_attach
  post 'conversations/:id/detach_doc/:doc_id' => 'conversations#detach_doc', as: :conv_doc_detach

  resources :contacts, only: [:index, :create, :destroy]

  resources :tasks
  post 'tasks/:id' => 'tasks#update_checklist', as: :update_checklist

  resources :events

  get 'activity' => 'application#panel_activity', as: :activity_popover
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :user_has_accesses, foreign_key: :document_id, :dependent => :destroy
  has_many :view_accesses, -> { where(access_type: 0) }, class_name: 'UserHasAccess', foreign_key: :document_id
  has_many :edit_accesses, -> { where(access_type: 1) }, class_name: 'UserHasAccess', foreign_key: :document_id
	has_many :users, through: :user_has_accesses, source: :user
	has_many :document_types, through: :document_has_types
	has_many :document_has_types, :dependent => :destroy
	has_many :child_documents, class_name: 'Document', foreign_key: :parent_directory, :dependent => :destroy
  belongs_to :document_folder, class_name: 'Document', foreign_key: :parent_directory
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_one :file_info, class_name: 'FileInfo', foreign_key: 'document_id', :dependent => :destroy

  has_and_belongs_to_many :tasks, join_table: :tasks_documents
  has_and_belongs_to_many :events, join_table: :events_documents
  has_and_belongs_to_many :conversations, join_table: :conversations_documents

  validates :description, length: { maximum: 256 }
  validates :tags, length: { maximum: 256 }

  scope :with_matched_field, ->(value, field) {fields=field.split(" "); where(Document.arel_table[fields[0]].matches('%' + value + '%')) || where(Document.arel_table[fields[1]].matches('%' + value + '%')) }

  def save_with_file(file)
    begin
      transaction do
          self.save!
          file.document_id = self.id
          file.save!
          return true
      end
    rescue ActiveRecord::StatementInvalid
      #error
    rescue
      return false
    end
  end

  def as_json(options = {})
    { id: id, text: title, children: doc_type == 0, icon: doc_type == 0 ? 'jstree-folder' : 'jstree-file' }
  end
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
	has_many :documents, through: :document_has_types
	has_many :document_has_types, dependent: :destroy
	validates_presence_of :title
	validates_length_of :title, :maximum => 45
	validates_uniqueness_of :title
end

app/controllers/documents_controller.rb
##
# This class represents a controller for all document related tasks.

class DocumentsController < ApplicationController
  def index
    if params[:id].blank?
      @docs = Document.where(parent_directory: nil, owner_id: current_user.id)
      @current_folder = nil
    else
      @docs = Document.where(parent_directory: params[:id], owner_id: current_user.id)
      @current_folder = Document.find_by_id_and_doc_type(params[:id], 0)
      not_found if @current_folder.nil?
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def shared
    @docs_personal_shared = current_user.personal_shared_documents

    # TODO (dkalpakchi): maybe this can be done via db query
    @docs_for_roles = current_user.role_shared_documents

    @docs = @docs_personal_shared.push(*@docs_for_roles).uniq

    unless @docs.nil?
      @folders = @docs.select { |doc| doc.doc_type == 0 }
      @files = @docs.select { |doc| doc.doc_type == 1 }
    end

    respond_to do |format|
      format.js
    end
  end

  def new
    #
    # It's assumed that the document can be created without a file (not sure why).
    # params[:documents][:newfile] is the actual file (if it's there)
    # If it's blank, we're just saving the document that's just a nutshell, basically,
    # otherwise we're saving both the document and the file.
    # The file is saved as FileInfo instance + actual file on hard drive
    #
    if params[:documents][:doctype] == 'folder'
      if create_document(0).save
        flash[:notice] = t('documents.folder_creation_success')
      else
        flash[:error] = t('documents.error_create')
      end
    elsif params[:documents][:new_file].blank?
      doc = create_document(1)
      if doc.save!
        flash[:notice] = t('documents.file_add_success')
      else
        flash[:error] = t('documents.error_create')
      end
    else
      doc = create_document(1)
      if save_file(doc)
        flash[:notice] = t('documents.file_add_success')
      else
        flash[:error] = t('documents.error_create')
      end
    end
    # TODO (dkalpakchi): change this to appropriate index handling
    Document.import force:true
    if request.referer.split('/')[3] == 'conversations'
      render json: {id: doc.id}
    else
      redirect_to action: 'index'
    end
  end

  def save_file(doc)
    file = FileInfo.new
    file.document_id = doc.id
    file.file = params[:documents][:new_file]
    doc.save_with_parameter(file)
  end

  def update_file(doc)
    file = doc.file_info
    file.file = params[:new_version]
    file.save
  end

  def create_document(type)
    doc = Document.new
    doc.title = params[:documents][:new_doc_title]
    doc.description = params[:documents][:description] if params[:documents][:description]
    doc.doc_type = type
    doc.parent_directory = params[:id]
    doc.owner_id = current_user.id

    owner_access = UserHasAccess.new
    owner_access.user_id = current_user.id
    owner_access.access_type = 1
    doc.save_with_parameter(owner_access)

    doc
  end

  def update
    @doc = Document.find(params[:id])
    if params[:document_types].present?
      @doc.document_types = params[:document_types].map {|t| DocumentType.find_or_create_by(title: t) }
    end
    params[:document][:for_roles] = User.roles_to_int(params[:document][:for_roles] || [])

    UserHasAccess.where(document: @doc).update_all(access_type: 0)

    if params[:personal_shared].present?
      # TODO: as create_or_update is deprecated, this method seems to be the only suitable,
      #       find out how to fix this to one DB query easily
      User.where(id: params[:personal_shared]).map { |u|
        UserHasAccess.find_or_create_by(document: @doc, user: u)
      }.each{|uha|
        uha.update_attributes(access_type: 2)
      }
    end

    if params[:new_version].present?
      update_file(@doc)
    end

    if @doc.update_attributes(document_params)
      redirect_to documents_path
    else
      render json: {
        :error => "Wrong params!"
      }
    end
  end

  def delete
    doc = Document.find(params[:id])
    current = doc.parent_directory
    puts current
    if !doc.nil? and doc.destroy
      flash[:notice] = t('documents.flash_removed_item')
    end
    redirect_to action: 'index', id: current
  end

  def change_file
    stat = 'error'
    if !params[:document][:doc_id].blank? and !params[:document][:new_file].blank?
      doc = Document.find(params[:document][:doc_id])
      if doc.file_info
        doc.file_info.file = params[:document][:new_file]
      else
        doc.file_info = FileInfo.new(document_id: params[:document][:doc_id], file: params[:document][:new_file])
      end
      stat = 'ok' if doc.file_info.save
    end

    respond_to do |format|
      format.json { render json: { status: stat, doc: doc ? doc.id : 0, title: doc.file_info.file_file_name, url: doc.file_info.file.url(:original, false) } }
    end
  end

  def search
    @files = nil

    if !params[:query].present?
      params[:query] = "*"
    end

    @files = elastic_search

    if params[:extended_search].present?
      extended_search(@files)
    end

    respond_to do |format|
      format.js
      format.json { render json: @files.to_json.html_safe }
    end
  end

  def get_file_doc_id
    @file = FileInfo.find_by(file_file_name: params[:file_name], file_file_size: params[:file_size])
    respond_to do |format|
      format.json { render json: { doc_id: @file.document_id } }
    end
  end

  def sidebar_info
    @doc = Document.find(params[:id])
    respond_to do |format|
      format.js {}
    end
  end

  private
  def elastic_search
    d = Document.__elasticsearch__
    r = d.search(params[:query])
    doc_ids = r.results.response.map {|r| r.id }
    if params[:current].present?
      @files = Document.where(id: doc_ids, parent_directory: params[:current], owner: current_user)
    else
      @files = Document.where(id: doc_ids, owner: current_user)
    end
    @files
  end

  def extended_search(files)
    ext_params = params[:extended_search]
  end

  def document_params
    params.require(:document)
      .permit(:title, :description, :for_roles)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def doc_format_icon(file)
    if file.file_info.present?
      case File.extname(file.file_info.file.path)
      when '.docx', '.doc'
        'file blue word outline icon'
      when '.xls', '.xlsx'
        'file green excel outline icon'
      when '.ppt', '.pptx'
        'file orange powerpoint outline icon'
      when '.pdf'
        'file red pdf outline icon'
      when '.png', '.jpg', '.jpeg', '.gif'
        'file yellow image outline icon'
      else
        'file outline icon'
      end
    else
      'file outline icon'
    end
  end
end

app/views/documents/_access_list.erb
<% accesses = access_type == '0' ? doc.view_accesses : doc.edit_accesses %>
<% accesses.each do |access| %>
    <%= link_to access.user.login, user_path(access.user_id), :target => :blank %>
    <%= link_to '/documents/update_lists', data: { method: :post, remote: true, params: { pk: access.document_id, access_id: access.id, access_type: access.access_type }.to_param } do %>
        <span class="glyphicon glyphicon-remove red"></span>
    <% end %>
    <br>
<% end %>

app/views/documents/_doc.html.erb
<% if doc.doc_type == 0 %>
  <%= render partial: 'folder', locals: { folder: doc } %>
<% else %>
  <%= render partial: 'file', locals: { file: doc } %>
<% end %>

app/views/documents/_file.erb
<% file_info = file.file_info %>
<% can_edit = file.edit_accesses.pluck(:user_id).include?(current_user.id) %>
<tr data-id="file" class="docs-title">
  <td><i class="<%= doc_format_icon(file) %>"></i></td>
  <td id="doc-title-<%= file.id %>"><%= file.title %></td>
  <td><%= file.document_types.pluck(:title).join ', ' %></td>
  <td><%= File.extname(file_info.file.path) if file_info %></td>
  <td><%= file.created_at.to_formatted_s :docs_time %></td>
  <td><%= file.updated_at.to_formatted_s :docs_time %></td>
  <td>
    <%= link_to file_info ? file_info.file.url(:original, false) : '', target: :blank, class: 'ui tiny circular blue icon button', data: {id: 'downloadFile'} do %>
      <i class='download icon'></i>
    <% end %>
  </td>
</tr>

<!-- <div class="ui simple dimmer">

</div> -->

app/views/documents/_folder.erb
<tr data-id="folder" data-link="<%= @shared ? document_shared_path(folder.owner_id, folder.id) : document_path(folder) %>" class="docs-title">
  <td><i class="folder icon"></i></td>
  <td><%= folder.title %></td>
  <td></td>
  <td><%= t('documents.folder') %></td>
  <td><%= folder.created_at.to_formatted_s :docs_time %></td>
  <td><%= folder.updated_at.to_formatted_s :docs_time %></td>
  <td></td>
</tr>

app/views/documents/_folder.html.erb
<tr data-id="folder" data-link="<%= @shared ? document_shared_path(folder.owner_id, folder.id) : document_path(folder) %>" class="docs-title">
  <td><i class="folder icon"></i></td>
  <td><%= folder.title %></td>
  <td></td>
  <td><%= t('documents.folder') %></td>
  <td><%= folder.created_at.to_formatted_s :docs_time %></td>
  <td><%= folder.updated_at.to_formatted_s :docs_time %></td>
  <td></td>
</tr>

app/views/documents/_search.erb
<%= form_tag documents_path, :method => 'get' do %>
<div class="panel  panel-primary">
  <div class="panel-heading docs-panel-heading">
    <h4 class="panel-title">
      <a class="accordion-toggle" data-toggle="collapse" href="#collapseSearch">
        <%= t('documents.search_by_docs') %>
      </a>
    </h4>
  </div>
  <div id="collapseSearch" class="panel-collapse collapse in">
    <div class="panel-body">
      <div class="parameter-group">
        <table>
          <tr>
            <td>
             <label class="checkbox-inline">
               <%= check_box_tag 'a_folder', true, params[:a_folder] %>
               <%= h t("documents.folders") %>
              </label>
            </td>
            <td>
              <label class="checkbox-inline">
                <%= check_box_tag 'are_owned', true, params[:are_owned] %>
                <%= h t("documents.owned") %>
              </label>
            </td>
          </tr>
          <tr>
            <td>
              <label class="checkbox-inline">
                <%= check_box_tag 'a_file', true, params[:a_file] %>
                <%= h t("documents.files") %>
              </label>
            </td>
            <td>
              <label class="checkbox-inline">
                <%= check_box_tag 'are_shared', true, params[:are_shared] %>
                <%= h t("documents.shared") %>
              </label>
            </td>
            <td>
              <label class="checkbox-inline">
                <%= check_box_tag 'new_shared', 1 %>
                <%= h t("documents.new_shared") %>
              </label>
            </td>
          </tr>
        </table>

        <div class="dates">
          <table>
            <tr>
              <td><%=t("documents.not_earlier")%></td>
              <td><input type="text" placeholder=<%=t("documents.yyyymmdd")%> class="form-control input-sm" name="after_date" value="<%= params[:after_date] %>" /></td>
            </tr>
            <tr>
              <td><%=t("documents.not_later")%></td>
              <td><input type="text" placeholder=<%=t("documents.yyyymmdd")%> class="form-control input-sm" name="before_date" value="<%= params[:before_date] %>" /></td>
            </tr>
          </table>
        </div>

        <div class="types">
          <%= t("documents.types") %>
          <div class="input-group">
            <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
              <span><%= t('util.all_of')+@types.first.title+"..." %></span>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu j-admin-search-type-combo">
              <% @types.each do |type| %>
                <li>
                  <label class="checkbox-inline"  >
                    <%= check_box_tag 'type_ids[]', type.id -%>
                    <%= type.title -%>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        </div>


        <div class="formats">
          <%= t("documents.formats") %>
          <div class="input-group">
            <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
              <span ><%= t('util.all_of')+(File.extname @formats.first.file_info.file.path)+"..." %></span>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu j-admin-search-type-combo">
              <% @formats.each do |format| %>
                <li>
                  <label class="checkbox-inline">
                    <%= check_box_tag 'format_ids[]', (File.extname format.file_info.file.path) -%>
                    <%= File.extname format.file_info.file.path -%>
                  </label>
                </li>
              <% end %>
            </ul>
          </div>
        </div>


      </div>
      <div class="input-group">
        <div class="input-group-btn">
          <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="j-admin-search-btn-text"><%= t('documents.by_' +params[:search_by]) %></span>
            <span class="caret"></span>
          </button>
          <input class="j-admin-search-type-input" type="hidden" name="search_by" value="<%= params[:search_by] %>" />
          <ul class="dropdown-menu j-admin-search-type-combo">
            <li><a href="#" data-search-type="title"><%= t('documents.by_title') %></a></li>
            <li><a href="#" data-search-type="tags"><%= t('documents.by_tags') %></a></li>
            <li><a href="#" data-search-type="title tags"><%= t('documents.by_title tags') %></a></li>
            <li><a href="#" data-search-type="description"><%= t('documents.by_description') %></a></li>
          </ul>
        </div>
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" />
        <span class="input-group-btn">
          <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span>
            <%= t('util.search') %>
          </button>
        </span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/documents/_types_list.erb
<% DocumentHasType.where(document_id: doc.id).each do |type| %>
    <%= type.document_type.title %>
    <%= link_to '/documents/update_lists', data: { method: :post, remote: true, params: { pk: doc.id, type_id: type.id }.to_param } do %>
        <span class="glyphicon glyphicon-remove red"></span>
    <% end %>
    <br>
<% end %>

app/views/documents/_user.erb
<tr class="docs-title" data-visible="<%= true %>">
  <td><span class="glyphicon glyphicon-user"></span></td>
  <td><%= user.login %></td>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td><%= format_roles(user.roles, ", ") %></td>
  <td>
    <%= link_to document_shared_root_path(user.id), :class => 'btn btn-success docs-navbar-tool' do %>
        <span class='glyphicon glyphicon-eye-open'></span>
        <%= t('documents.open') %>
    <% end %>
  </td>
</tr>

app/views/documents/index.html.erb
<section class="ui piled segment">
  <h1><%= t('documents.documents') %></h1>
  <section class="ui divided grid">
    <div class="four wide column">
      <div class="ui fluid vertical menu">
        <a class="active teal item">
          <%= t('documents.recently_used') %>
          <div class="ui teal label">1</div>
        </a>
        <a class="item">
          <%= t('documents.yours') %>
          <div class="ui label">1</div>
        </a>
        <a class="item">
          <%= t('documents.shared') %>
          <div class="ui label">51</div>
        </a>
        <a class="item">
          <%= t('documents.by_type') %>
          <div class="ui label">1</div>
        </a>
        <div class="item">
          <div class="ui small icon input">
            <input placeholder="<%= t('documents.search_by_docs') %>..." type="text">
            <i class="search icon"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="twelve wide column">
      <table id="docs" class="ui sortable table segment">
        <thead>
          <tr>
            <th><%= t('documents.title') %></th>
            <th><%= t('documents.type') %></th>
            <th><%= t('documents.format') %></th>
            <th><%= t('documents.date_created') %></th>
            <th><%= t('documents.date_changed') %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>John</td>
            <td>No Action</td>
            <td>None</td>
            <td>None</td>
            <td>None</td>
          </tr>
          <tr>
            <td>Jamie</td>
            <td class="positive">Approved</td>
            <td class="warning">Requires call</td>
            <td>None</td>
            <td>None</td>
          </tr>
          <tr>
            <td>Jill</td>
            <td class="negative">Denied</td>
            <td>None</td>
            <td>None</td>
            <td>None</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</section>

<%= render 'documents/modals/document_select' %>
<%= render 'documents/modals/new_file' %>
<%= render 'documents/modals/new_folder' %>
<%= render 'documents/modals/confirm_remove' %>
<%= render 'documents/modals/search_user' %>
<%= render 'documents/modals/search_type' %>

<%= render 'search' %>
<%= render 'folder_info' if !@current_folder.nil? %>

<div class="text-center">
<% if !@shared || @can_edit_current_folder %>
  <%= link_to '', :data => { :toggle => 'modal', :target => '#modal_add_file' }, :class => 'btn btn-success' do %>
      <span class='glyphicon glyphicon-cloud-upload'></span>
      <%= t('documents.add_doc') %>
  <% end %>

  <%= link_to '', :data => { :toggle => 'modal', :target => '#modal_add_folder' }, :class => 'btn btn-success' do %>
      <span class='glyphicon glyphicon-cloud-upload'></span>
      <%= t('documents.add_folder') %>
  <% end %>

  <%= link_to '/documents/shared', :class => 'btn btn-info' do %>
      <span class='glyphicon glyphicon-retweet'></span>
      <%= t('documents.shared_docs') %>
  <% end %>
<% else %>
    <%= link_to '/documents', :class => 'btn btn-info' do %>
        <span class='glyphicon glyphicon-user'></span>
        <%= t('documents.owned_docs') %>
    <% end %>
<% end %>
</div>

<br>

<div class="panel panel-primary">
  <div class="panel-heading">
    <%= t('documents.docs_in_cur_dir') %>
    <% if !@current_folder.nil? %>
        <%= link_to @current_folder.parent_directory.nil? ? documents_path : document_path(@current_folder.parent_directory), :class => 'btn-sm btn-success docs-up-folder-btn' do %>
            <span class='glyphicon glyphicon-upload'></span>
            <%= t('documents.up_folder') %>
        <% end %>
    <% end %>
  </div>
    <table id="documents-table" class="table table-striped table-verticle-centered" style="table-layout:fixed;">
      <thead>
      <tr>
        <th style="width: 3%"></th>
        <th style="width: 27%"><%= t('documents.title') %></th>
        <th style="width: 25%"><%= t('documents.type') %></th>
        <th style="width: 8%"><%= t('documents.format') %></th>
        <th style="width: 10%"><%= t('documents.date_created') %></th>
        <th style="width: 10%"><%= t('documents.date_changed') %></th>
        <th style="width: 11%"></th>
      </tr>
      </thead>

      <tbody>
        <%= render partial: 'file', collection: @files %>
        <%= render partial: 'folder', collection: @folders %>
      </tbody>
    </table>
</div>

<div class="panel-body text-center">
  <%= paginate @docs %>
</div>

app/views/documents/jstree.json.erb
<%= @docs.to_json.html_safe %>

app/views/documents/search.js.erb
$('table#docs tbody').empty()
$("table#docs tbody").append(
	"<%= escape_javascript(render(partial: 'file', collection: @files) || \
	'<tr><td class="center aligned" colspan="7">'.html_safe << t('documents.not_found') << '</td></tr>'.html_safe) %>"
)

app/views/documents/shared.js.erb
$('table#docs tbody').empty()
$("table#docs tbody").append(
  "<%= escape_javascript(render(partial: 'file', collection: @files) || \
  '<tr><td class="center aligned" colspan="7">'.html_safe << t('documents.not_found') << '</td></tr>'.html_safe) %>"
)

app/views/documents/sidebar_info.js.erb
<%= render(partial: 'documents/file_info', locals: { doc: Document.find(@doc) }) %>

app/views/documents/update_lists.js.erb
$('#modal_search_user').modal('hide');
$('#modal_search_type').modal('hide');

<% if @access_type.nil? %>
    $('#docs-types-list-<%= @doc.id %>').html('<%= escape_javascript(render :partial => 'types_list', :locals => { doc: @doc }) %>');
<% else %>
    $('#docs-<%= @access_type == '0' ? 'view' : 'edit' %>-access-list-<%= @doc.id %>').html('<%= escape_javascript(render :partial => 'access_list', :locals => { doc: @doc, access_type: @access_type }) %>');
<% end %>