config/routes.rb
AcDP::Application.routes.draw do
  opinio_model

  resources :news_posts do
    member do
      delete 'icon'
    end
    collection do
      get 'tags/:tag' => 'news_posts#index', as: 'tag'
      get 'categories/:category' => 'news_posts#index', as: 'category'
      get 'categories/group/:group_id' => 'news_posts#index', as: 'group'
    end
  end

  get 'calendar', to: 'calendar'
  get 'calendar/day/:date', to: 'calendar#day', as: 'day'

  get 'documents/sidebar_info' => 'documents#sidebar_info', as: 'documents_sidebar_info'
  get 'documents', to: 'documents#index'
  get 'documents/search' => 'documents#search', as: 'doc_search'
  get 'documents/shared', to: 'documents#shared', as: 'doc_shared'
  # get 'documents/shared/:user_id', to: 'documents#shared', as: 'document_shared_root'
  # get 'documents/shared/:user_id/:id', to: 'documents#shared', as: 'document_shared'
  get 'documents/get_file_info', to: 'documents#get_file_doc_id', as: 'get_file_doc_id'
  get 'documents/:id', to: 'documents#index', as: 'document'

  post 'documents', to: 'documents#new', as: 'new_document'
  post 'documents/:id', to: 'documents#new', as: 'document_new'
  post 'documents/change_file', to: 'documents#change_file'

  patch 'documents/:id', to: 'documents#update'

  delete 'documents/:id/delete', to: 'documents#delete', as: 'document_delete'

  root "users#dashboard"

  devise_for :users

  namespace :admin do
    resources :users do
      member do
        delete "avatar"
      end
    end
    resources :groups
    resources :doctypes
  end

  get 'dashboard' => "users#dashboard", as: :dashboard

  resources :users, only: [:show] do
  	collection do
      get 'current/edit' => "users#edit_current", as: :current_user_edit
      patch 'current' => "users#update_current", as: :current_user_update
      delete 'current' => "users#avatar", as: :current_user_avatar
  	end
  end

  resources :conversations, only: [:create, :index, :destroy] do
    resources :messages, only: [:index, :create]
  end

  post 'conversations/:id/attach_doc/:doc_id' => 'conversations#attach_doc', as: :conv_doc_attach
  post 'conversations/:id/detach_doc/:doc_id' => 'conversations#detach_doc', as: :conv_doc_detach

  resources :contacts, only: [:index, :create, :destroy]

  resources :tasks
  post 'tasks/:id' => 'tasks#update_checklist', as: :update_checklist

  resources :events

  get 'activity' => 'application#panel_activity', as: :activity_popover
end

app/views/documents_pin/_pin_doc_modal.html.haml
#addDocModal.ui.modal
  %i.close.icon
  .header
    = modal_title
  #content.content
    #searchDocForm.ui.fluid.form.segment{data: { 'search-url' => doc_search_path(format: :json) }}
      .field
        = label_tag 'query', t('documents.title')
        = text_field_tag 'query', ''
      = button_tag t('documents.pin'), id: pinBtnId, class: "ui positive button"
    #docSearchResults.ui.cards
      

app/views/documents_pin/_pin_doc_upload_choice_modal.html.haml
#docUploadChoice.ui.basic.modal.transition
  %i.close.icon
  .header
    = t('documents.uploading')
  #content.image.content
    .image
      %i.cloud.upload.icon
    .description
      %p= t('documents.upload_from')
  .actions
    = form_for(:documents, url: new_document_path, method: :post, remote: true, html: { class: 'ui fluid form', id: 'docToPin', data: {url: get_file_doc_id_path}}) do |f|
      = f.hidden_field :doc_type, value: 'file'
      = f.text_field :new_doc_title, id: 'title', class: 'hidden'
      = f.text_field :description, id: 'description', class: 'hidden'
      = file_field :documents, :new_file, id: 'docFromPCInput', class: 'hidden'
      .two.fluid.ui.buttons
        #pinDocFromWarehouse.ui.positive.button
          = t('documents.from_warehouse')
        .or
        #pinDocFromPC.ui.teal.button
          = t('documents.from_pc')

app/views/documents_pin/_pinned_doc.html.haml
.ui.label{data: {document: 'attached'}}
  %input{type: 'hidden', name: 'documents[]', value: doc.id}
  = doc.title
  - file_info = doc.file_info
  -if show
    -if file_info.present?
      = link_to file_info.file.url(:original, false), target: :blank do
        %i.download.disk.icon
    -else
      = link_to document_path(doc.parent_directory), target: :blank do
        %i.info.icon
  -else
    %i.delete.icon

app/views/documents_pin/_pinned_doc_ext.html.haml
.card.extended-doc{data: {document: 'attached', id: doc.id}}    
  .content
    %i.right.floated.delete.icon{data: {aim: 'detach'}}
    - file_info = doc.file_info
    -if file_info.present?
      = link_to file_info.file.url(:original, false) do
        %i.right.floated.download.disk.icon
    -else
      - parent = doc.parent_directory
      = link_to (parent ? document_path(parent) : documents_path) do
        %i.right.floated.info.icon
    .header= doc.title.truncate(20)
    .description= doc.description.present? ? doc.description.truncate(33) : t('documents.no_description')